-- =========================================================================
-- MFG Advisory — Fase 2: Seed af eksisterende standardindhold
-- =========================================================================
-- Kør EFTER migration_v2_production.sql. Sikker at køre flere gange —
-- alle indsættelser er lavet med ON CONFLICT DO NOTHING / DO UPDATE, så
-- der aldrig opstår dubletter, uanset hvor mange gange filen køres.
-- =========================================================================

-- -------------------------------------------------------------------------
-- Sidetekster (page_content) — udtrukket automatisk fra det nuværende,
-- allerede godkendte indhold på hjemmesiden (ingen ny/opdigtet tekst).
-- -------------------------------------------------------------------------
insert into page_content (page, section, field, value, content_type, status) values ('index', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'nav', 'nav-cta-text', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'hero', 'hero-eyebrow', 'MFG Advisory', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'hero', 'hero-body', 'Vi hjælper ejerledere og SMV''er med at udvikle ledere, styrke samarbejdet og skabe resultater gennem ordentlighed, respekt og empati.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'hero', 'hero-cta-primary', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'meet_morten', 'meet-morten-label', 'Mød Morten', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'meet_morten', 'meet-morten-title', 'Rådgivning fra én, der selv har stået med ansvaret', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'meet_morten', 'meet-morten-body-1', 'Vi hjælper ejerledere og ledelsesteams med at skabe tydelig retning, udvikle mennesker og omsætte strategi til målbare resultater.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'meet_morten', 'meet-morten-body-2', 'Med mere end 20 års erfaring fra ledelse og operationel drift har vi en stærk praktisk forståelse for de situationer, hvor mennesker, kultur, ledelse og forretning skal fungere samtidig.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'meet_morten', 'meet-morten-body-3', 'Vi kender også konsekvenserne, når man vælger den forkerte vej. Derfor bygger vores rådgivning på ordentlighed, respekt, empati og løsninger, der kan fungere i praksis.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'meet_morten', 'meet-morten-cta-secondary', 'Læs om Morten', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'meet_morten', 'meet-morten-cta-primary', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'foredrag_teaser', 'foredrag-teaser-label', 'Foredrag', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'foredrag_teaser', 'foredrag-teaser-title', 'Perspektiver, der kan bruges i praksis', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'foredrag_teaser', 'foredrag-teaser-text', 'Book et praksisnært foredrag om mennesker, ledelse, kultur, psykologisk tryghed eller forretningsudvikling – tilpasset jeres organisation og deltagere.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'foredrag_teaser', 'foredrag-teaser-cta', 'Se alle foredrag', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('index', 'footer', 'footer-copyright', '© 2026 MFG Advisory · Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'nav', 'nav-cta-text', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-h1', 'Det rigtige match begynder med mennesket bag CV''et', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-intro-1', 'At ramme rigtigt fra første dag er afgørende. Matcher mennesket bag CV''et jeres team, kultur og organisation, øger I sandsynligheden for bedre trivsel, hurtigere integration og lavere personaleomsætning.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-intro-2', 'Har I brug for hjælp til rekruttering, personprofiler eller en mere struktureret onboarding, hjælper vi jer med at skabe et forløb, hvor både virksomheden og den nye medarbejder får den bedst mulige start.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-cta-question', 'Skal vi finde det rigtige match?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-cta-button', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-challenge', 'Stillinger står åbne for længe, nye medarbejdere matcher ikke rollen eller kulturen, og onboarding er tilfældig snarere end struktureret.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-benefit-1', 'Hurtigere rekruttering', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-benefit-2', 'Bedre match', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-benefit-3', 'Lavere personaleomsætning', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-benefit-4', 'Stærkere onboarding', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc1-title', 'Rekruttering', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc1-desc', 'Målrettet rekrutteringsproces fra behovsafklaring over kandidatvurdering til onboarding — så den nye medarbejder rammer rigtigt fra dag ét.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc1-long', 'Vi bygger rekrutteringsprocessen op omkring den reelle kravprofil — ikke en generisk stillingsskabelon. Fra behovsafklaring med den ansættende leder, over struktureret kandidatvurdering, til en onboarding-plan der sikrer, at den nye medarbejder er produktiv fra dag ét.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc1-challenges', 'Stillinger, der står åbne for længe. Kandidater, der ser rigtige ud på papiret men ikke passer til kulturen. Onboarding, der er tilfældig og afhænger af, hvem der lige har tid.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc1-approach', 'Vi starter med en skarp kravprofil, bruger strukturerede samtaler frem for mavefornemmelse, og lader IPA nordic-profiler kvalificere — ikke afgøre — den endelige beslutning.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc1-results', 'Kortere time-to-hire, færre fejlansættelser og en onboarding, der er ens, uanset hvem der ansætter.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc1-cta', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc2-title', 'Personprofiler (IPA nordic)', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc2-desc', 'Præcis indsigt i adfærd, motivation og potentiale. Bruges til rekruttering, udvikling og sammensætning af stærkere teams.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc2-long', 'IPA nordic-profiler bruges systematisk gennem hele medarbejderrejsen — fra rekruttering, over udvikling af eksisterende medarbejdere, til sammensætning af teams, der reelt komplementerer hinanden.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc2-challenges', 'Beslutninger om ansættelse og forfremmelse baseret på mavefornemmelse. Teams, der er sammensat tilfældigt frem for bevidst. Udviklingssamtaler uden et fælles sprog for adfærd og motivation.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc2-approach', 'Profilen bruges som samtaleredskab, ikke facitliste — den kvalificerer dialogen mellem leder og medarbejder, og gør det muligt at sætte ord på styrker og udviklingspotentiale.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc2-results', 'Mere præcise ansættelser, stærkere teamsammensætning og udviklingssamtaler med substans.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-svc2-cta', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-case-title', 'Produktionsvirksomhed, ca. 60 medarbejdere', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-case-situation', 'Høj udskiftning i produktionen og lang tid til besættelse af ledige stillinger.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-case-retning', 'Mennesker — rekrutteringsproces og personprofiler.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-case-losning', 'Ny kravprofil, struktureret samtaleguide og IPA nordic-profiler i udvælgelsen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-case-resultat', 'Kortere time-to-hire og markant færre opsigelser i prøvetiden.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-case-note', 'Illustrativt forløb baseret på typiske engagementer. Erstattes med dokumenteret case ved go-live.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-insight1-q', 'Derfor koster en fejlansættelse mere, end du tror', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-insight1-a', 'De direkte omkostninger er sjældent problemet — det er tidsforbruget, den tabte produktivitet og den kultur-smitte, en forkert ansættelse efterlader i teamet.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-insight2-q', 'Sådan bruges personprofiler rigtigt', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-insight2-a', 'En profil er et samtaleredskab, ikke en facitliste. Værdien ligger i, hvordan den bruges til at kvalificere samtalen — ikke i at erstatte den.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-cta-text', 'Vil du vide, hvor jeres største potentiale ligger inden for Mennesker?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'hero', 'mennesker-cta-button', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mennesker', 'footer', 'footer-copyright', '© 2026 MFG Advisory · Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'nav', 'nav-cta-text', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-h1', 'Skaber jeres ledelse tydelig retning i hverdagen?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-intro-1', 'Når mål, ansvar og forventninger er uklare, bruger medarbejdere og ledere unødvendig tid på misforståelser, brandslukning og skiftende prioriteringer.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-intro-2', 'Vi hjælper jer med at skabe en tydeligere ledelsesretning, styrke ledernes gennemslagskraft og omsætte beslutninger til handling i organisationen. Det giver større ansvar, bedre samarbejde og mere konsekvent opfølgning.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-cta-question', 'Har jeres ledere brug for en tydeligere fælles retning?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-cta-button', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-challenge', 'Beslutninger trækker ud, ledere mangler et rum til sparring, og prioriteringen skifter, alt efter hvem der råber højest.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-benefit-1', 'Hurtigere beslutninger', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-benefit-2', 'Stærkere ledere', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-benefit-3', 'Bedre prioritering', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-benefit-4', 'Mere retning', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc1-title', 'Ledelse &amp; Coaching', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc1-desc', 'Ledelsessparring og coaching, der styrker beslutningskraft, retning og gennemslagskraft hos den enkelte leder.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc1-long', 'Individuel ledelsessparring, der tager udgangspunkt i lederens konkrete udfordringer — ikke en generisk lederuddannelse. Faste samtaler over en periode, med fokus på beslutningskraft, retning og gennemslagskraft.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc1-challenges', 'Beslutninger, der trækker ud. Nye ledere, der mangler et rum til at tænke højt. Prioritering, der skifter alt efter hvem der råber højest.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc1-approach', 'Fast, tilbagevendende sparring — ofte månedligt — kombineret med konkret træning i de samtaler og beslutninger, lederen reelt står overfor lige nu.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc1-results', 'Hurtigere og mere konsistente beslutninger, en tydeligere ledelsesstil og en leder, organisationen kan følge.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc1-cta', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc2-title', 'Interim Ledelse', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc2-desc', 'Erfaren ledelseskraft i en periode med forandring, vakance eller vækst — indtil den faste organisation er på plads.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc2-long', 'Erfaren ledelseskraft, der træder ind i en periode med forandring, vakance eller vækst — og sikrer, at driften og udviklingen fortsætter, mens den faste organisation falder på plads.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc2-challenges', 'En ledervakance, der trækker ud. Forandringer, der kræver erfaren ledelse, ingen i organisationen har tid eller erfaring til at bære alene lige nu.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc2-approach', 'Vi går ind som en del af ledelsen i en afgrænset periode, med klare mål for, hvornår og hvordan opgaven afsluttes og overdrages.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc2-results', 'Kontinuitet i driften, fremdrift i forandringen og en velforberedt overdragelse til den faste organisation.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-svc2-cta', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-case-title', 'Ejerledet handelsvirksomhed, generationsskifte', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-case-situation', 'Ny direktør efter generationsskifte, usikker på egen ledelsesstil og prioritering.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-case-retning', 'Ledelse — individuel sparring over seks måneder.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-case-losning', 'Fast sparring, klar prioriteringsmodel og træning i svære samtaler.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-case-resultat', 'Hurtigere beslutninger og en ledelsesstil, organisationen kunne følge.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-case-note', 'Illustrativt forløb baseret på typiske engagementer. Erstattes med dokumenteret case ved go-live.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-insight1-q', 'Hvorfor de fleste ledere mangler sparring, ikke viden', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-insight1-a', 'De fleste ledere ved godt, hvad de burde gøre. Det, der mangler, er et rum til at tænke højt, før beslutningen træffes — ikke bagefter.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-insight2-q', 'Prioritering er en ledelsesdisciplin, ikke en to-do-liste', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-insight2-a', 'Når alt er vigtigt, er intet det. God prioritering handler om at sige nej tydeligt — og stå ved det.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-cta-text', 'Vil du styrke ledelseskraften i din organisation?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'hero', 'ledelse-cta-button', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('ledelse', 'footer', 'footer-copyright', '© 2026 MFG Advisory · Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'nav', 'nav-cta-text', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-h1', 'Understøtter jeres kultur de resultater, I ønsker?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-intro-1', 'Kultur skabes ikke af værdier på en væg, men af den adfærd, der accepteres, gentages og belønnes i hverdagen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-intro-2', 'Vi hjælper jer med at gøre den ønskede kultur konkret og anvendelig. Sammen skaber vi tydeligere fælles standarder, stærkere samarbejde og en organisation, hvor mennesker forstår både retningen og deres eget ansvar.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-cta-question', 'Skal jeres kultur være en styrke frem for en barriere?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-cta-button', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-challenge', 'Samarbejdet knirker på tværs af teams, ansvar er uklart, og sygefravær eller lav trivsel begynder at kunne mærkes på bundlinjen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-benefit-1', 'Højere engagement', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-benefit-2', 'Lavere sygefravær', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-benefit-3', 'Bedre samarbejde', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-benefit-4', 'Stærkere ansvarskultur', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc1-title', 'Teamudvikling', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc1-desc', 'Konkret teamarbejde, der styrker tillid, samarbejde og fælles spilleregler — bygget på virksomhedens egen hverdag, ikke generiske øvelser.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc1-long', 'Konkret teamarbejde bygget på virksomhedens egen hverdag — ikke generiske øvelser fra en skabelon. Vi arbejder med de faktiske samarbejdsudfordringer, teamet står overfor.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc1-challenges', 'Samarbejde, der knirker på tværs af afdelinger eller funktioner. Uklare spilleregler for, hvordan teamet reelt arbejder sammen. Konflikter, der ulmer uden at blive adresseret.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc1-approach', 'Workshopforløb med afsæt i teamets egne situationer, tydelige aftaler om samarbejde, og opfølgning der sikrer, at aftalerne bliver til vane.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc1-results', 'Stærkere samarbejde, færre eskalerede konflikter og et team, der løser uenigheder, før de vokser sig store.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc1-cta', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc2-title', 'Ledelse &amp; Coaching', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc2-desc', 'Ledere sætter kulturen. Coaching af ledergruppen skaber konsistens i den adfærd, der reelt smitter af på organisationen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc2-long', 'Ledere sætter kulturen — bevidst eller ubevidst. Coaching af ledergruppen skaber konsistens i den adfærd, der reelt smitter af på resten af organisationen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc2-challenges', 'Ledere, der siger ét og gør noget andet. Uens ledelsesstil på tværs af afdelinger, der skaber forvirring om, "hvordan vi gør her".', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc2-approach', 'Coaching af ledergruppen samlet og individuelt, med fokus på den adfærd der faktisk former kulturen i det daglige.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc2-results', 'En mere konsistent ledelseskultur og ledere, der aktivt går forrest i den kultur, virksomheden ønsker.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-svc2-cta', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-case-title', 'Servicevirksomhed, to afdelinger i konflikt', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-case-situation', 'Samarbejdet mellem to afdelinger var præget af mistillid og uklare ansvarsområder.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-case-retning', 'Kultur — teamudvikling på tværs af afdelingerne.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-case-losning', 'Fælles workshopforløb, tydelige snitflader og faste samarbejdsaftaler.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-case-resultat', 'Færre eskalerede konflikter og hurtigere afklaring i det daglige samarbejde.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-case-note', 'Illustrativt forløb baseret på typiske engagementer. Erstattes med dokumenteret case ved go-live.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-insight1-q', 'Kultur er det, der sker, når ingen ser på', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-insight1-a', 'Værdier på væggen ændrer ingenting. Kultur skabes i de tusind små beslutninger, medarbejderne træffer, når ledelsen ikke er til stede.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-insight2-q', 'Ansvarskultur starter med tydelighed, ikke kontrol', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-insight2-a', 'Jo mere uklart ansvaret er, jo mere kontrol kræver det. Tydelighed er den billigste vej til ejerskab.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-cta-text', 'Vil du styrke samarbejdet og ansvarskulturen i teamet?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'hero', 'kultur-cta-button', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kultur', 'footer', 'footer-copyright', '© 2026 MFG Advisory · Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'nav', 'nav-cta-text', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-h1', 'Bliver jeres potentiale omsat til målbare resultater?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-intro-1', 'Gode ambitioner skaber ikke resultater alene. De skal omsættes til tydelige prioriteringer, ansvar, handling og løbende opfølgning.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-intro-2', 'Vi hjælper jer med at skabe sammenhæng mellem strategi og daglig drift, så organisationens tid, kompetencer og ressourcer bruges dér, hvor de skaber størst værdi for kunderne og forretningen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-cta-question', 'Skal vi omsætte jeres ambitioner til konkrete handlinger?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-cta-button', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-challenge', 'Strategien er klar, men eksekveringen halter, systemerne er utidssvarende, og administrationen fylder mere end den skaber værdi.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-benefit-1', 'Mere vækst', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-benefit-2', 'Bedre eksekvering', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-benefit-3', 'Bedre kundeoplevelser', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-benefit-4', 'Højere indtjening', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc1-title', 'HR-systemer', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc1-desc', 'Uvildig rådgivning om valg og implementering af HR-systemer, herunder PeopleSuite. Ingen leverandørbinding — kun det, der passer til jeres drift.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc1-long', 'Uvildig rådgivning om valg og implementering af HR-systemer. Vi repræsenterer ikke nogen leverandør — kun det, der reelt passer til jeres drift og fremtidige behov.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc1-challenges', 'Manuelle processer, der ikke længere hænger sammen med virksomhedens størrelse. Usikkerhed om, hvilket system der reelt passer — presset af leverandører med egen agenda.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc1-approach', 'Uvildig kravspecifikation og systemvurdering, efterfulgt af en realistisk implementeringsplan tilpasset jeres kapacitet.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc1-results', 'Mindre administration, bedre datagrundlag for ledelsen og et system, der passer til jeres drift — ikke omvendt.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc1-cta', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc2-title', 'Strategisk Sparring', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc2-desc', 'Sparring på strategi, eksekvering og organisatorisk retning for ejerledere og ledelsesteam, der skal omsætte planer til handling.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc2-long', 'Sparring på strategi, eksekvering og organisatorisk retning for ejerledere og ledelsesteam, der skal omsætte planer til konkret handling.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc2-challenges', 'En strategi, der er god på papiret, men aldrig rigtig bliver til handling. Ledelsesteams, der er enige om målet, men uenige om vejen derhen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc2-approach', 'Regelmæssig sparring med fokus på eksekvering — ikke endnu en strategiproces, men hjælp til at omsætte den strategi, I allerede har.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc2-results', 'Bedre eksekvering, klarere prioritering i ledelsesteamet og fremdrift på de initiativer, der reelt driver forretningen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-svc2-cta', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-case-title', 'Voksende SMV, manuelle HR-processer', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-case-situation', 'Vækst i medarbejderantal havde overhalet virksomhedens manuelle HR-processer.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-case-retning', 'Forretning — valg og implementering af HR-system.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-case-losning', 'Uvildig systemvurdering, kravspecifikation og implementeringsplan.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-case-resultat', 'Betydeligt mindre administration og bedre datagrundlag for ledelsen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-case-note', 'Illustrativt forløb baseret på typiske engagementer. Erstattes med dokumenteret case ved go-live.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-insight1-q', 'Det rigtige HR-system er det, ingen lægger mærke til', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-insight1-a', 'Det bedste system er ikke det med flest funktioner — det er det, der understøtter jeres processer så gnidningsfrit, at ingen taler om det.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-insight2-q', 'Strategi dør i eksekveringen, ikke i planlægningen', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-insight2-a', 'De fleste strategier er gode nok. Det, der afgør resultatet, er om ledelsen formår at omsætte den til beslutninger i hverdagen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-cta-text', 'Vil du styrke eksekveringen og indtjeningen i din forretning?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'hero', 'forretning-cta-button', 'Book en samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('forretning', 'footer', 'footer-copyright', '© 2026 MFG Advisory · Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('foredrag', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('foredrag', 'nav', 'nav-cta-text', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('foredrag', 'general', 'foredrag-h1', 'Foredrag, der skaber refleksion, retning og handling', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('foredrag', 'general', 'foredrag-intro-1', 'Vi tilbyder praksisnære foredrag om mennesker, ledelse, kultur og forretning. Foredragene bygger på mere end 20 års erfaring med ledelse og operationel drift og omsætter komplekse udfordringer til konkrete perspektiver, som deltagerne kan bruge i deres egen hverdag.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('foredrag', 'general', 'foredrag-intro-2', 'Uanset om målgruppen er ledere, medarbejdere, ejerledere eller ledelsesteams, tilpasses indhold og eksempler til organisationens situation og formålet med arrangementet.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('foredrag', 'general', 'foredrag-cta-primary', 'Forespørg på et foredrag', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('foredrag', 'general', 'foredrag-cta-secondary', 'Se foredragene', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('foredrag', 'footer', 'footer-copyright', '© 2026 MFG Advisory · Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'nav', 'nav-cta-text', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'general', 'cases-h1', 'Cases og dokumenterede resultater', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'general', 'cases-intro', 'Fire eksempler på, hvad der sker, når indsatsen sættes ind det rigtige sted i The MFG Compass™.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'general', 'cases-teaser-mennesker-title', 'Produktionsvirksomhed, ca. 60 medarbejdere', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'general', 'cases-teaser-mennesker-desc', 'Kortere time-to-hire og markant færre opsigelser i prøvetiden efter ny rekrutteringsproces og IPA nordic-profiler.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'general', 'cases-teaser-ledelse-title', 'Ejerledet handelsvirksomhed, generationsskifte', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'general', 'cases-teaser-ledelse-desc', 'Hurtigere beslutninger og en ledelsesstil, organisationen kunne følge, efter et halvt års fast sparring.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'general', 'cases-teaser-kultur-title', 'Servicevirksomhed, to afdelinger i konflikt', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'general', 'cases-teaser-kultur-desc', 'Færre eskalerede konflikter og hurtigere afklaring i det daglige samarbejde efter fælles teamudviklingsforløb.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'general', 'cases-teaser-forretning-title', 'Voksende SMV, manuelle HR-processer', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'general', 'cases-teaser-forretning-desc', 'Betydeligt mindre administration og bedre datagrundlag efter uvildig valg og implementering af HR-system.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('cases', 'footer', 'footer-copyright', '© 2026 MFG Advisory · Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('om-morten', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('om-morten', 'nav', 'nav-cta-text', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('om-morten', 'om_morten', 'om-name', 'Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('om-morten', 'om_morten', 'om-role', 'Founder &amp; Senior Advisor, MFG Advisory.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('om-morten', 'global', 'contact-email', 'morten@mfgadvisory.dk', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('om-morten', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('om-morten', 'om_morten', 'om-bio-1', 'Morten Foged Guglielmetti hjælper virksomheder med at omsætte strategi til handling gennem stærk ledelse, organisationsudvikling og AI-understøttet forretningsudvikling.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('om-morten', 'om_morten', 'om-bio-2', 'Fokus er at skabe varige resultater gennem mennesker, struktur og eksekvering.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('om-morten', 'footer', 'footer-copyright', '© 2026 MFG Advisory · Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'nav', 'nav-cta-text', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'hero', 'kontakt-hero-title', 'Vi skaber resultater gennem relationer, struktur og stærk kommerciel forståelse.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'hero', 'kontakt-hero-body', 'Vi hjælper ejerledere og ledelsesteams med at skabe retning, udvikle mennesker og omsætte strategi til målbare resultater gennem The MFG Compass™.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'global', 'contact-email', 'morten@mfgadvisory.dk', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'hero', 'kontakt-form-title', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'hero', 'kontakt-form-sub', 'Udfyld formularen, så vender vi tilbage hurtigst muligt — typisk inden for 1-2 hverdage.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'hero', 'kontakt-person-name', 'Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'hero', 'kontakt-person-role', 'Founder &amp; Senior Advisor', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'hero', 'kontakt-person-bio', '20+ års erfaring med ledelse og operationel drift. Rådgivning bygget på ordentlighed, respekt og empati — med fokus på målbare resultater.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'hero', 'kontakt-closing', 'Lad os finde jeres retning i kompasset.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('kontakt', 'footer', 'footer-copyright', '© 2026 MFG Advisory · Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'global', 'contact-phone', '+45 60 52 89 00', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'nav', 'nav-cta-text', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-hero-title', 'Udvikling virker først, når helheden hænger sammen', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-hero-intro', 'The MFG Compass™ samler mennesker, ledelse, kultur og forretning i én fælles retning. Metoden skaber et klart billede af, hvor organisationen står, hvor potentialet ligger, og hvad der skal prioriteres for at omsætte ambitioner til målbare resultater.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-people-text', 'Vi ser mennesket, før vi ser rollen. Udvikling begynder med forståelse for kompetencer, motivation, ansvar og potentiale.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-leadership-text', 'Vi skaber retning gennem ledelse. Tydelige valg, klare forventninger og konsekvent opfølgning gør strategien anvendelig i hverdagen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-culture-text', 'Vi bygger en kultur, hvor mennesker lykkes. Adfærd, samarbejde og fælles standarder skal understøtte den retning, virksomheden ønsker.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-business-text', 'Vi omsætter potentiale til resultater. Udviklingen skal kunne mærkes i drift, kunder, økonomi og organisationens evne til at levere.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-step1-title', 'Afklaring', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-step1-text', 'Vi afdækker virksomhedens situation, mål og vigtigste udfordringer.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-step2-title', 'Analyse', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-step2-text', 'De fire retninger vurderes samlet for at finde ubalancer, styrker og uudnyttet potentiale.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-step3-title', 'Prioritering', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-step3-text', 'Vi vælger de indsatser, der skaber størst effekt og tydeligst retning.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-step4-title', 'Forankring', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-step4-text', 'Løsningerne omsættes til handling, ansvar og opfølgning i organisationen.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-why-text', 'En stærk strategi skaber ikke resultater alene. Den skal bæres af ledelsen, forstås af menneskerne og understøttes af kulturen. Omvendt skaber trivsel og engagement heller ikke varige resultater, hvis retning, ansvar og kommercielt fokus mangler. The MFG Compass™ gør sammenhængene synlige og skaber et fælles grundlag for beslutninger og udvikling.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-cta-title', 'Hvor peger jeres kompas hen?', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-cta-text', 'En strategisk samtale kan være første skridt til at skabe klarhed over retning, potentiale og de vigtigste næste handlinger.', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'hero', 'mfgcompass-cta-button', 'Book en strategisk samtale', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;
insert into page_content (page, section, field, value, content_type, status) values ('mfg-compass', 'footer', 'footer-copyright', '© 2026 MFG Advisory · Morten Foged Guglielmetti', 'text', 'published') on conflict (page, section, field) do update set value = excluded.value;

-- -------------------------------------------------------------------------
-- SEO-metadata — udtrukket fra <title> og <meta name="description"> på
-- hver side.
-- -------------------------------------------------------------------------
insert into seo_metadata (page, title, meta_description, status) values ('index', 'MFG Advisory — The MFG Compass™', 'MFG Advisory hjælper ejerledere og SMV''er med at omsætte strategi til resultater gennem The MFG Compass™ — mennesker, ledelse, kultur og forretning.', 'published') on conflict (page) do update set title = excluded.title, meta_description = excluded.meta_description;
insert into seo_metadata (page, title, meta_description, status) values ('mennesker', 'Mennesker — The MFG Compass™ | MFG Advisory', 'Det rigtige match, fra rekruttering til onboarding — løsninger under Mennesker i The MFG Compass™.', 'published') on conflict (page) do update set title = excluded.title, meta_description = excluded.meta_description;
insert into seo_metadata (page, title, meta_description, status) values ('ledelse', 'Ledelse — The MFG Compass™ | MFG Advisory', 'Stærkere ledere, hurtigere beslutninger — løsninger under Ledelse i The MFG Compass™.', 'published') on conflict (page) do update set title = excluded.title, meta_description = excluded.meta_description;
insert into seo_metadata (page, title, meta_description, status) values ('kultur', 'Kultur — The MFG Compass™ | MFG Advisory', 'Stærkere samarbejde og en tydelig ansvarskultur — løsninger under Kultur i The MFG Compass™.', 'published') on conflict (page) do update set title = excluded.title, meta_description = excluded.meta_description;
insert into seo_metadata (page, title, meta_description, status) values ('forretning', 'Forretning — The MFG Compass™ | MFG Advisory', 'Bedre eksekvering og en tydelig vej til vækst — løsninger under Forretning i The MFG Compass™.', 'published') on conflict (page) do update set title = excluded.title, meta_description = excluded.meta_description;
insert into seo_metadata (page, title, meta_description, status) values ('foredrag', 'Foredrag om ledelse, kultur og forretningsudvikling | MFG Advisory', 'Book et praksisnært foredrag med Morten Foged Guglielmetti om ledelse, kultur, mennesker, forretningsudvikling, psykologisk tryghed og The MFG Compass™.', 'published') on conflict (page) do update set title = excluded.title, meta_description = excluded.meta_description;
insert into seo_metadata (page, title, meta_description, status) values ('cases', 'Cases og dokumenterede resultater — MFG Advisory', 'Fire eksempler på dokumenterede resultater fra The MFG Compass™.', 'published') on conflict (page) do update set title = excluded.title, meta_description = excluded.meta_description;
insert into seo_metadata (page, title, meta_description, status) values ('om-morten', 'Om Morten Foged Guglielmetti — MFG Advisory', 'Morten Foged Guglielmetti, Founder & Senior Advisor hos MFG Advisory.', 'published') on conflict (page) do update set title = excluded.title, meta_description = excluded.meta_description;
insert into seo_metadata (page, title, meta_description, status) values ('kontakt', 'Kontakt — MFG Advisory', 'Book en strategisk samtale med MFG Advisory.', 'published') on conflict (page) do update set title = excluded.title, meta_description = excluded.meta_description;
insert into seo_metadata (page, title, meta_description, status) values ('mfg-compass', 'The MFG Compass™ — Sådan fungerer metoden — MFG Advisory', 'Sådan hænger Mennesker, Ledelse, Kultur og Forretning sammen i The MFG Compass™ — Mortens metode til at skabe retning og målbare resultater.', 'published') on conflict (page) do update set title = excluded.title, meta_description = excluded.meta_description;
-- -------------------------------------------------------------------------
-- Cases — de fire eksisterende eksempler fra cases.html. Kun titel,
-- kategori og kort beskrivelse fandtes som strukturerede felter i det
-- tidligere system; de øvrige felter (challenge, responsibility, approach,
-- result, mfg_help, key_figures) er bevidst efterladt TOMME her, så der
-- ikke opdigtes indhold, der ikke fandtes. Morten kan udfylde dem i
-- adminpanelet, når han har de præcise informationer.
-- -------------------------------------------------------------------------
insert into cases (slug, title, category, teaser, status, sort_order, published_at) values ('mennesker-case-1', 'Produktionsvirksomhed, ca. 60 medarbejdere', 'mennesker', 'Kortere time-to-hire og markant færre opsigelser i prøvetiden efter ny rekrutteringsproces og IPA nordic-profiler.', 'published', 1, now()) on conflict (slug) do update set title = excluded.title, category = excluded.category, teaser = excluded.teaser;
insert into cases (slug, title, category, teaser, status, sort_order, published_at) values ('ledelse-case-1', 'Ejerledet handelsvirksomhed, generationsskifte', 'ledelse', 'Hurtigere beslutninger og en ledelsesstil, organisationen kunne følge, efter et halvt års fast sparring.', 'published', 2, now()) on conflict (slug) do update set title = excluded.title, category = excluded.category, teaser = excluded.teaser;
insert into cases (slug, title, category, teaser, status, sort_order, published_at) values ('kultur-case-1', 'Servicevirksomhed, to afdelinger i konflikt', 'kultur', 'Færre eskalerede konflikter og hurtigere afklaring i det daglige samarbejde efter fælles teamudviklingsforløb.', 'published', 3, now()) on conflict (slug) do update set title = excluded.title, category = excluded.category, teaser = excluded.teaser;
insert into cases (slug, title, category, teaser, status, sort_order, published_at) values ('forretning-case-1', 'Voksende SMV, manuelle HR-processer', 'forretning', 'Betydeligt mindre administration og bedre datagrundlag efter uvildig valg og implementering af HR-system.', 'published', 4, now()) on conflict (slug) do update set title = excluded.title, category = excluded.category, teaser = excluded.teaser;

-- -------------------------------------------------------------------------
-- Foredrag — de syv eksisterende standardforedrag (samme tekster som i
-- assets/js/default-talks.js).
-- -------------------------------------------------------------------------
insert into talks (slug, title, category, teaser, cta_text, cta_url, status, sort_order, is_featured, published_at) values ('ledelse-der-skaber-retning', 'Ledelse, der skaber retning', 'ledelse', 'Et foredrag om tydelig ledelse, ansvar, beslutningskraft og evnen til at omsætte mål til handling i en travl hverdag.', 'Forespørg på foredraget', 'kontakt.html', 'published', 1, true, now()) on conflict (slug) do update set title = excluded.title, category = excluded.category, teaser = excluded.teaser;
insert into talks (slug, title, category, teaser, cta_text, cta_url, status, sort_order, is_featured, published_at) values ('kultur-skabes-gennem-handling', 'Kultur skabes gennem handling', 'kultur', 'Et foredrag om den adfærd, de vaner og de fælles standarder, der former organisationens kultur og resultater.', 'Forespørg på foredraget', 'kontakt.html', 'published', 2, false, now()) on conflict (slug) do update set title = excluded.title, category = excluded.category, teaser = excluded.teaser;
insert into talks (slug, title, category, teaser, cta_text, cta_url, status, sort_order, is_featured, published_at) values ('mennesket-bag-rollen', 'Mennesket bag rollen', 'mennesker', 'Et foredrag om rekruttering, potentiale, motivation, personprofiler og betydningen af det rigtige match mellem menneske og organisation.', 'Forespørg på foredraget', 'kontakt.html', 'published', 3, true, now()) on conflict (slug) do update set title = excluded.title, category = excluded.category, teaser = excluded.teaser;
insert into talks (slug, title, category, teaser, cta_text, cta_url, status, sort_order, is_featured, published_at) values ('fra-potentiale-til-resultater', 'Fra potentiale til forretningsmæssige resultater', 'forretning', 'Et foredrag om at skabe forbindelse mellem strategi, mennesker, prioriteringer og den daglige drift.', 'Forespørg på foredraget', 'kontakt.html', 'published', 4, false, now()) on conflict (slug) do update set title = excluded.title, category = excluded.category, teaser = excluded.teaser;
insert into talks (slug, title, category, teaser, cta_text, cta_url, status, sort_order, is_featured, published_at) values ('psykologisk-tryghed', 'Psykologisk tryghed med tydelige forventninger', 'psykologisk-tryghed', 'Et foredrag om at skabe et miljø, hvor mennesker tør bidrage, stille spørgsmål og sige fra – uden at tydelighed, ansvar og resultater forsvinder.', 'Forespørg på foredraget', 'kontakt.html', 'published', 5, false, now()) on conflict (slug) do update set title = excluded.title, category = excluded.category, teaser = excluded.teaser;
insert into talks (slug, title, category, teaser, cta_text, cta_url, status, sort_order, is_featured, published_at) values ('tilknytning-i-en-tid-med-forandring', 'Tilknytning i en tid med forandring', 'tilknytning', 'Et foredrag om, hvad der får mennesker til at engagere sig, føle tilhørsforhold og vælge at blive i organisationen.', 'Forespørg på foredraget', 'kontakt.html', 'published', 6, false, now()) on conflict (slug) do update set title = excluded.title, category = excluded.category, teaser = excluded.teaser;
insert into talks (slug, title, category, teaser, cta_text, cta_url, status, sort_order, is_featured, published_at) values ('mfg-compass-navigation-under-pres', 'The MFG Compass™ – Navigation under pres', 'compass', 'Et foredrag om at navigere, prioritere og bevare retningen, når organisationen oplever pres, forandringer eller modstridende krav.', 'Forespørg på foredraget', 'kontakt.html', 'published', 7, true, now()) on conflict (slug) do update set title = excluded.title, category = excluded.category, teaser = excluded.teaser;
-- -------------------------------------------------------------------------
-- Testimonials — INGEN findes i det eksisterende indhold (der er aldrig
-- oprettet opdigtede kundeudtalelser). Denne tabel efterlades derfor
-- bevidst tom. Morten tilføjer rigtige testimonials via adminpanelet,
-- når han har dem.
-- -------------------------------------------------------------------------
-- (ingen rækker at indsætte)